language: php
sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate

install:
  - composer update

script:
   - ./vendor/bin/behat
